name: 'Inventory-Service CI/CD Pipeline'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_USER: ${{ vars.JFROG_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
          JF_PROJECT: "bookverse"
          JFROG_CLI_BUILD_NAME: ${{ github.event.repository.name }}
          JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}

      - name: Configure Artifactory for Python
        run: |
          jfrog pipc --repo-resolve=bookverse-pypi-local

      - name: Install Python dependencies with JFrog CLI
        run: |
          jfrog pip install -r requirements.txt

      - name: Set Unique SemVer Version
        id: set_version
        run: |
          VERSION="1.3.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and Push Backend Image
        run: |
          REGISTRY_URL=$(echo "${{ vars.JFROG_URL }}" | sed 's|https://||')
          IMAGE_TAG="$REGISTRY_URL/bookverse-docker-internal/${{ github.event.repository.name }}-backend:${{ steps.set_version.outputs.VERSION }}"
          jfrog docker build --pull -t $IMAGE_TAG \
            --build-arg JFROG_URL=${{ vars.JFROG_URL }} \
            --build-arg JFROG_USER=${{ vars.JFROG_USER }} \
            --build-arg JFROG_ACCESS_TOKEN=${{ secrets.JFROG_ACCESS_TOKEN }} \
            -f Dockerfile.backend .
          jfrog rt dp $IMAGE_TAG bookverse-docker-internal --build-name=${{ github.event.repository.name }} --build-number=${{ github.run_number }}

      - name: Build and Push Frontend Image
        run: |
          REGISTRY_URL=$(echo "${{ vars.JFROG_URL }}" | sed 's|https://||')
          IMAGE_TAG="$REGISTRY_URL/bookverse-docker-internal/${{ github.event.repository.name }}-frontend:${{ steps.set_version.outputs.VERSION }}"
          jfrog docker build --pull -t $IMAGE_TAG -f Dockerfile.frontend .
          jfrog rt dp $IMAGE_TAG bookverse-docker-internal --build-name=${{ github.event.repository.name }} --build-number=${{ github.run_number }}

      - name: Collect Git information for Build Info
        run: |
          jfrog rt bag ${{ github.event.repository.name }} ${{ github.run_number }}

      - name: Collect Environment Variables for Build Info
        run: |
          jfrog rt bce ${{ github.event.repository.name }} ${{ github.run_number }}

      - name: Publish Build Info
        run: |
          jfrog rt bp ${{ github.event.repository.name }} ${{ github.run_number }}

      - name: Create Microservice Release Bundle
        run: |
          jfrog rbc ${{ github.event.repository.name }} ${{ steps.set_version.outputs.VERSION }} --project=bookverse --build-name=${{ github.event.repository.name }} --build-number=${{ github.run_number }}

      - name: Create and Attach Build Link Evidence
        run: |
          cat <<EOF > build-link-evidence.json
          {
            "builder": { "id": "uri:github-actions" },
            "runId": { "workflow_run_id": "${{ github.run_id }}" }
          }
          EOF

          jf evd create --predicate build-link-evidence.json \
          --predicate-type https://in-toto.io/attestation/link/v0.3 \
          --release-bundle ${{ github.event.repository.name }} --release-bundle-version ${{ steps.set_version.outputs.VERSION }} \
          --project bookverse --key "${{ secrets.BOOKVERSE_KEY }}"
 
  promote-bundle:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_URL }}
          JF_USER: ${{ vars.JFROG_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
          JF_PROJECT: "bookverse"

      - name: Create and Attach Commit Review Evidence (Pre-DEV Gate)
        run: |
          cat <<EOF > commit-review.json
          {
            "attributes": [
              { "name": "committer", "value": "${{ github.actor }}" },
              { "name": "reviewer", "value": "code-owner@bookverse.com" },
              { "name": "review_status", "value": "Approved" },
              { "name": "review_date", "value": "Jun 2, 2025 10:23:16 UTC" }
            ]
          }
          EOF

          jf evd create --predicate commit-review.json \
          --predicate-type https://in-toto.io/attestation/scai/attribute-report \
          --release-bundle ${{ github.event.repository.name }} --release-bundle-version ${{ needs.build-and-publish.outputs.version }} \
          --project bookverse --key "${{ secrets.BOOKVERSE_KEY }}"

      - name: Promote to DEV
        run: |
          jfrog rbp ${{ github.event.repository.name }} ${{ needs.build-and-publish.outputs.version }} DEV --promotion-type=move --include-repos=bookverse-docker-internal

      - name: Create and Attach DEV Smoke Test Evidence (QA Gate)
        run: |
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat <<EOF > dev-smoke-test.json
          {
            "summary": {
              "result": "PASSED",
              "timestamp": "$timestamp",
              "test_suite": "Smoke Tests (ran in DEV)",
              "total_tests": 3,
              "passed": 3,
              "failed": 0,
              "duration_seconds": 12.34
            },
            "tests": [
              { "name": "API Endpoint Connectivity", "status": "PASSED", "duration_ms": 150 },
              { "name": "Database Connection", "status": "PASSED", "duration_ms": 75 },
              { "name": "Frontend Load Test", "status": "PASSED", "duration_ms": 12115 }
            ]
          }
          EOF

          jf evd create --predicate dev-smoke-test.json \
          --predicate-type https://in-toto.io/attestation/test-result/v0.1 \
          --release-bundle ${{ github.event.repository.name }} --release-bundle-version ${{ needs.build-and-publish.outputs.version }} \
          --project bookverse --key "${{ secrets.BOOKVERSE_KEY }}"
        
      - name: Promote to QA
        run: |
          jfrog rbp ${{ github.event.repository.name }} ${{ needs.build-and-publish.outputs.version }} QA --promotion-type=move --include-repos=bookverse-docker-internal

      - name: Create and Attach QA Test & Jira Evidence (STAGE Gate)
        run: |
          echo '{
            "result": "PASSED",
            "duration": "125s",
            "passed": 345,
            "failed": 0,
            "skipped": 2,
            "test_suite": "QA Regression Suite (ran in QA)"
          }' > qa-test-results.json
          echo '{
            "attributes": [
              {
                "name": "jira_integration",
                "value": {
                  "server_url": "https://bookverse.atlassian.net",
                  "query": "fixVersion = ${{ needs.build-and-publish.outputs.version }} AND status in (Resolved, Closed)",
                  "issues_found": 2,
                  "issues": [
                    { "key": "BOOK-101", "summary": "UI glitch on checkout page for large orders", "status": "Closed", "priority": "High" },
                    { "key": "BOOK-105", "summary": "API returns 500 error when book stock is zero", "status": "Resolved", "priority": "Medium" }
                  ]
                }
              }
            ]
          }' > qa-jira-issues.json
          jf evd create --predicate qa-test-results.json \
          --predicate-type https://in-toto.io/attestation/test-result/v0.1 \
          --release-bundle ${{ github.event.repository.name }} --release-bundle-version ${{ needs.build-and-publish.outputs.version }} \
          --project bookverse --key "${{ secrets.BOOKVERSE_KEY }}"

          jf evd create --predicate qa-jira-issues.json \
          --predicate-type hhttps://in-toto.io/attestation/scai/attribute-report \
          --release-bundle ${{ github.event.repository.name }} --release-bundle-version ${{ needs.build-and-publish.outputs.version }} \
          --project bookverse --key "${{ secrets.BOOKVERSE_KEY }}"

      - name: Promote to STAGE
        run: |
          jfrog rbp ${{ github.event.repository.name }} ${{ needs.build-and-publish.outputs.version }} STAGE --promotion-type=move --include-repos=bookverse-docker-internal

      - name: Create and Attach STAGE Sign-off & Trace Evidence (PROD Gate)
        run: |
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat <<EOF > stage-signoff.json
          {
            "attributes": [
              { "name": "quality_gate_passed", "value": true },
              { "name": "approved_by", "value": "product-manager@bookverse.com" },
              { "name": "approval_date", "value": "$timestamp" }
            ]
          }
          EOF
          echo '{
            "trace_id": "trace-xyz-9876",
            "environment": "STAGE",
            "status": "SUCCESS",
            "duration": "7200s",
            "details": "Application ran successfully under load test in staging environment."
          }' > stage-runtime-trace.json

          jf evd create --predicate tage-signoff.json \
          --predicate-type https://in-toto.io/attestation/scai/attribute-report \
          --release-bundle ${{ github.event.repository.name }} --release-bundle-version ${{ needs.build-and-publish.outputs.version }} \
          --project bookverse --key "${{ secrets.BOOKVERSE_KEY }}"

          jf evd create --predicate tage-runtime-trace.json \
          --predicate-type https://in-toto.io/attestation/runtime-trace/v0.1 \
          --release-bundle ${{ github.event.repository.name }} --release-bundle-version ${{ needs.build-and-publish.outputs.version }} \
          --project bookverse --key "${{ secrets.BOOKVERSE_KEY }}"

      - name: Promote to PROD
        run: |
          jfrog rbp ${{ github.event.repository.name }} ${{ needs.build-and-publish.outputs.version }} PROD --promotion-type=move --include-repos=bookverse-docker-internal-prod
